Repository mash-up-kr/DHC-Android, pull requests merged in 2025-07, with the labels that each got.

#275 [#267] 홈화면 소비분석도 리롤되도록 수정
  core/designsystem/src/main/kotlin/com/dhc/designsystem/mission/DhcCardReRoll.kt
  core/designsystem/src/main/kotlin/com/dhc/designsystem/mission/SpendingHabitMissionCard.kt
  presentation/home/src/main/java/com/dhc/home/main/HomeMissionComponent.kt
  presentation/home/src/main/java/com/dhc/home/main/HomeScreen.kt
  presentation/home/src/main/java/com/dhc/home/main/MissionChange.kt
Labels: Feature

#308 [#284] Splash 에 관련 로직 적용
  core/presentation/build.gradle.kts
  core/presentation/src/main/java/com/dhc/presentation/component/LottieView.kt
  gradle/libs.versions.toml
  presentation/intro/src/main/assets/splash_animation.json
  presentation/intro/src/main/java/com/dhc/intro/splash/SplashContract.kt
  presentation/intro/src/main/java/com/dhc/intro/splash/SplashRoute.kt
  presentation/intro/src/main/java/com/dhc/intro/splash/SplashScreen.kt
  presentation/intro/src/main/java/com/dhc/intro/splash/SplashViewModel.kt
Labels: Feature

#309 [#269] 홈화면 오늘 미션 끝내기 로직 추가 및 이미지 수정
  core/common/src/main/kotlin/com/dhc/common/FormatterUtil.kt
  data/src/main/kotlin/com/dhc/dhcandroid/datasource/DhcRemoteDataSource.kt
  data/src/main/kotlin/com/dhc/dhcandroid/datasource/DhcRemoteDataSourceImpl.kt
  data/src/main/kotlin/com/dhc/dhcandroid/repository/DhcRepository.kt
  data/src/main/kotlin/com/dhc/dhcandroid/repository/DhcRepositoryImpl.kt
  data/src/main/kotlin/com/dhc/dhcandroid/service/DhcService.kt
  presentation/home/src/main/java/com/dhc/home/HomeRoute.kt
  presentation/home/src/main/java/com/dhc/home/HomeViewModel.kt
  presentation/home/src/main/java/com/dhc/home/main/HomeContract.kt
  presentation/home/src/main/java/com/dhc/home/main/HomeScreen.kt
  presentation/home/src/main/java/com/dhc/home/main/MissionSuccessDialog.kt
  presentation/home/src/main/res/drawable-hdpi/mission_success.png
  presentation/home/src/main/res/drawable-xxhdpi/mission_success.png
  presentation/home/src/main/res/drawable-xxxhdpi/mission_success.png
  presentation/home/src/main/res/drawable/mission_success.png
Labels: Feature

#311 [#310] 오늘 미션 끝내기 여부 API 파라미터 추가 및 미션 완료 시 리롤 안되도록
  core/designsystem/src/main/kotlin/com/dhc/designsystem/mission/DhcCardReRoll.kt
  data/src/main/kotlin/com/dhc/dhcandroid/model/HomeViewResponse.kt
  presentation/home/src/main/java/com/dhc/home/HomeViewModel.kt
  presentation/home/src/main/java/com/dhc/home/main/HomeContract.kt
  presentation/home/src/main/java/com/dhc/home/main/HomeMissionComponent.kt
  presentation/home/src/main/java/com/dhc/home/main/HomeScreen.kt
  presentation/home/src/main/java/com/dhc/home/main/MissionChange.kt
  presentation/home/src/main/java/com/dhc/home/model/HomeUiModel.kt
Labels: Feature

#318 [#281] 뒤로가기로 돌아올 경우 깜빡 거리는 이슈 해결
  core/presentation/src/main/java/com/dhc/presentation/component/VideoView.kt
  presentation/intro/src/main/java/com/dhc/intro/start/IntroStartScreen.kt
Labels: Bug

#313 [#285] 인트로 동영상 적용 및 변경된 디자인사항 적용
  app/src/main/java/com/dhc/dhcandroid/navigation/ContainerColor.kt
  app/src/main/java/com/dhc/dhcandroid/navigation/DhcApp.kt
  app/src/main/java/com/dhc/dhcandroid/navigation/DhcRoute.kt
  app/src/main/java/com/dhc/dhcandroid/navigation/ScreenConfig.kt
  core/presentation/src/main/java/com/dhc/presentation/component/VideoView.kt
  presentation/intro/src/main/java/com/dhc/intro/start/IntroStartRoute.kt
  presentation/intro/src/main/java/com/dhc/intro/start/IntroStartScreen.kt
  presentation/intro/src/main/java/com/dhc/intro/start/IntroStartViewModel.kt
  presentation/intro/src/main/res/drawable/intro_start_video_thumbnail.png
  presentation/intro/src/main/res/drawable/intro_thumbnail.png
  presentation/intro/src/main/res/raw/intro_start_video.mp4
  presentation/intro/src/main/res/raw/intro_video.mp4
  presentation/intro/src/main/res/values/strings.xml
Labels: Feature

#317 [#251]금전운 로딩 폴링 구현
  presentation/home/src/main/java/com/dhc/home/HomeViewModel.kt
Labels: Feature

#331 [#332] 초기화 이후 로딩 무한반복 되는 현상 수정
  data/src/main/kotlin/com/dhc/dhcandroid/datasource/DhcRemoteDataSource.kt
  data/src/main/kotlin/com/dhc/dhcandroid/datasource/DhcRemoteDataSourceImpl.kt
  data/src/main/kotlin/com/dhc/dhcandroid/repository/DhcRepository.kt
  data/src/main/kotlin/com/dhc/dhcandroid/repository/DhcRepositoryImpl.kt
  data/src/main/kotlin/com/dhc/dhcandroid/service/DhcService.kt
  presentation/mypage/src/main/kotlin/com/dhc/mypage/MyPageViewModel.kt
Labels: Bug

#338 User Id 보여지게 추가
  app/src/main/java/com/dhc/dhcandroid/MainViewModel.kt
  data/src/main/kotlin/com/dhc/dhcandroid/repository/AuthDataStoreRepository.kt
  data/src/main/kotlin/com/dhc/dhcandroid/repository/AuthDataStoreRepositoryImpl.kt
  presentation/mypage/src/main/kotlin/com/dhc/mypage/MyPageContract.kt
  presentation/mypage/src/main/kotlin/com/dhc/mypage/MyPageViewModel.kt
  presentation/mypage/src/main/kotlin/com/dhc/mypage/ui/MyPageScreen.kt
Labels: Feature

#344 [#341] generate-aab github action 수정
  .github/workflows/generate-aab.yaml
Labels: Bug

#343 [#342] 앱 이름 변경
  app/src/main/res/values/strings.xml
Labels: Bug

#349 [#348] Intro Mission 내용 추가
  presentation/intro/src/main/java/com/dhc/intro/mission/IntroMissionScreen.kt
Labels: Bug

#352 [#336] 인트로쪽 뒤로가기 버튼 아이콘 변경
  core/designsystem/src/main/kotlin/com/dhc/designsystem/topbar/DhcBasicTopBar.kt
  core/designsystem/src/main/res/drawable/ico_chevron_left.xml
Labels: Bug

#353 [#319] 인트로 시작화면에서 다음으로 넘어갔다가 바로 뒤로가기로 되돌아오면 동영상 안보이는 이슈 수정
  app/src/main/java/com/dhc/dhcandroid/navigation/DhcNavHost.kt
  presentation/intro/src/main/java/com/dhc/intro/start/IntroStartScreen.kt
Labels: Bug

#354 [#294] TopBar 랑 BottomBar 에 대해서 생겨나고 사라질 때 애니메이션 적용하기
  core/designsystem/src/main/kotlin/com/dhc/designsystem/gnb/DhcBottomBar.kt
  core/designsystem/src/main/kotlin/com/dhc/designsystem/topbar/DhcTopBar.kt
Labels: Bug

#359 [#357] 운세상세의 팁 카드 양쪽 높이값이 다르면 동일하게 맞도록 변경
  core/designsystem/src/main/kotlin/com/dhc/designsystem/tipcard/DhcTipCardGrid.kt
Labels: Bug

#367 [#366] 금전운 상세 파라미터 변경(아이콘 미노출)
  core/designsystem/src/main/kotlin/com/dhc/designsystem/tipcard/DhcTipCard.kt
  data/src/main/kotlin/com/dhc/dhcandroid/model/FortuneResponse.kt
  presentation/home/src/main/java/com/dhc/home/detail/utils/Extensions.kt
Labels: Refactory

#373 [#355] 우측상단 Gradient offset 억지 적용 때문에 Gradient 화면 이동시 버벅이는 느낌 수정
  app/src/main/java/com/dhc/dhcandroid/navigation/ContainerBackground.kt
  app/src/main/java/com/dhc/dhcandroid/navigation/ContainerColor.kt
  app/src/main/java/com/dhc/dhcandroid/navigation/DhcApp.kt
  app/src/main/java/com/dhc/dhcandroid/navigation/DhcRoute.kt
  app/src/main/java/com/dhc/dhcandroid/navigation/ScreenConfig.kt
  core/designsystem/src/main/kotlin/com/dhc/designsystem/gnb/DhcBottomBar.kt
  core/designsystem/src/main/kotlin/com/dhc/designsystem/topbar/DhcTopBar.kt
  core/presentation/src/main/java/com/dhc/presentation/component/LottieView.kt
  presentation/home/src/main/java/com/dhc/home/HomeRoute.kt
  presentation/home/src/main/java/com/dhc/home/main/HomeFlipCardScreen.kt
  presentation/home/src/main/java/com/dhc/home/main/HomeLoadingScreen.kt
  presentation/home/src/main/java/com/dhc/home/main/HomeScreen.kt
  presentation/intro/src/main/java/com/dhc/intro/fortunedetail/IntroFortuneDetailRoute.kt
Labels: Bug

#374 [#282] HomeScreen 내적으로 이동할 때 Crossfade 적용
  presentation/home/src/main/java/com/dhc/home/HomeRoute.kt
Labels: Feature

#391 [#379] click 시 Event 보내도록 처리
  presentation/home/src/main/java/com/dhc/home/main/HomeScreen.kt
Labels: Bug

#392 [#378] Intro 운세상세 color 안보여줘야 하는 부분 null 처리
  presentation/intro/src/main/java/com/dhc/intro/fortunedetail/IntroFortuneDetailViewModel.kt
Labels: Bug

#400 [#399] 인트로 비디오 리소스 수정
  presentation/intro/src/main/res/drawable/intro_start_video_thumbnail.png
  presentation/intro/src/main/res/raw/intro_start_video.mp4
Labels: Feature

#402 [#377] 인트로 시작화면 동영상 실행될때 바탕화면 나갔다오면 영상 꺼짐 이슈
  core/presentation/src/main/java/com/dhc/presentation/component/VideoView.kt
  presentation/intro/src/main/java/com/dhc/intro/start/IntroStartRoute.kt
  presentation/intro/src/main/java/com/dhc/intro/start/IntroStartScreen.kt
Labels: Bug

#376 [#375] 유저 정보 제거 API 생성 및 적용
  data/src/main/kotlin/com/dhc/dhcandroid/datasource/DhcRemoteDataSource.kt
  data/src/main/kotlin/com/dhc/dhcandroid/datasource/DhcRemoteDataSourceImpl.kt
  data/src/main/kotlin/com/dhc/dhcandroid/model/LogoutResponse.kt
  data/src/main/kotlin/com/dhc/dhcandroid/repository/DhcRepository.kt
  data/src/main/kotlin/com/dhc/dhcandroid/repository/DhcRepositoryImpl.kt
  data/src/main/kotlin/com/dhc/dhcandroid/service/DhcService.kt
  presentation/mypage/src/main/kotlin/com/dhc/mypage/MyPageContract.kt
  presentation/mypage/src/main/kotlin/com/dhc/mypage/MyPageRoute.kt
  presentation/mypage/src/main/kotlin/com/dhc/mypage/MyPageViewModel.kt
Labels: Bug

#390 [#368] 홈 로딩 데이터도 서버 데이터 쓰도록 수정
  core/common/src/main/kotlin/com/dhc/common/FormatterUtil.kt
  presentation/home/src/main/java/com/dhc/home/HomeRoute.kt
  presentation/home/src/main/java/com/dhc/home/main/HomeFlipCardScreen.kt
Labels: Feature

#398 [#320] 토스트 이전꺼 취소하고 뜨도록 수정
  core/designsystem/src/main/kotlin/com/dhc/designsystem/snackbar/DhcSnackBar.kt
  core/designsystem/src/main/kotlin/com/dhc/designsystem/snackbar/SnackBarUtil.kt
  presentation/home/src/main/java/com/dhc/home/HomeRoute.kt
Labels: Bug, Refactory

#388 릴리즈 배포 시 자동 태그 되도록 CI 추가
  .github/workflows/auto-release-tag.yaml
Labels: Enviroment

#404 [#403] intro lottie animation 수정
  presentation/intro/src/main/assets/splash_animation.json
Labels: Feature

#408 [#293] Firebase Crashlytics 적용
  app/build.gradle.kts
  build.gradle.kts
  gradle/libs.versions.toml
Labels: Enviroment

#396 [#329] 홈로딩/홈/금전운 상세 서버에서 카드이미지 가져오도록 수정
  data/src/main/kotlin/com/dhc/dhcandroid/model/DailyFortune.kt
  data/src/main/kotlin/com/dhc/dhcandroid/model/DailyFortuneResponse.kt
  data/src/main/kotlin/com/dhc/dhcandroid/model/FortuneResponse.kt
  data/src/main/kotlin/com/dhc/dhcandroid/model/HomeViewResponse.kt
  presentation/home/src/main/java/com/dhc/home/HomeRoute.kt
  presentation/home/src/main/java/com/dhc/home/detail/utils/Extensions.kt
  presentation/home/src/main/java/com/dhc/home/main/HomeFlipCardScreen.kt
  presentation/home/src/main/java/com/dhc/home/main/HomeScreen.kt
  presentation/home/src/main/java/com/dhc/home/model/TodayDailyFortuneUiModel.kt
Labels: Refactory

#425 [#412] 미션상세 이동 시 크래시나는 현상 수정
  core/common/src/main/kotlin/com/dhc/common/StringExt.kt
  core/designsystem/src/main/kotlin/com/dhc/designsystem/tipcard/DhcTipCard.kt
Labels: Bug

#426 [#416, #418] 미션페이지/마이페이지 백그라운드 수정
  app/src/main/java/com/dhc/dhcandroid/navigation/DhcRoute.kt
  presentation/mypage/src/main/kotlin/com/dhc/mypage/ui/MyPageScreen.kt
Labels: Bug

#427 [#422] 앱 초기화버튼 리플영역 수정
  presentation/mypage/src/main/kotlin/com/dhc/mypage/ui/settinglist/SettingList.kt
  presentation/mypage/src/main/kotlin/com/dhc/mypage/ui/settinglist/SettingNormalItem.kt
  presentation/mypage/src/main/kotlin/com/dhc/mypage/ui/settinglist/SettingToggleItem.kt
Labels: Bug

#430 [#419] 미션 현황 - 캘린더 스크롤 안되도록 수정
  core/designsystem/src/main/kotlin/com/dhc/designsystem/calendar/ui/DhcCalendarDate.kt
Labels: Bug

#424 [#411] 다시 불러올 때 homeState 변경하기
  data/src/main/kotlin/com/dhc/dhcandroid/datasource/FortuneDataSource.kt
  data/src/main/kotlin/com/dhc/dhcandroid/datasource/FortuneDataSourceImpl.kt
  data/src/main/kotlin/com/dhc/dhcandroid/di/DatasourceModule.kt
  data/src/main/kotlin/com/dhc/dhcandroid/di/RepositoryModule.kt
  data/src/main/kotlin/com/dhc/dhcandroid/repository/FortuneRepository.kt
  data/src/main/kotlin/com/dhc/dhcandroid/repository/FortuneRepositoryImpl.kt
  data/src/main/proto/user_preferences.proto
  presentation/home/src/main/java/com/dhc/home/HomeViewModel.kt
  presentation/mypage/src/main/kotlin/com/dhc/mypage/MyPageViewModel.kt
Labels: Bug

#435 [#432] 캘린더 캐시 남아있는 현상 수정
  data/src/main/kotlin/com/dhc/dhcandroid/repository/DhcRepository.kt
  data/src/main/kotlin/com/dhc/dhcandroid/repository/DhcRepositoryImpl.kt
  presentation/home/src/main/java/com/dhc/home/HomeViewModel.kt
  presentation/mypage/src/main/kotlin/com/dhc/mypage/MyPageViewModel.kt
Labels: Bug

#436 [#433] 금전운 상세보기 데이터 비어 있는 현상 수정
  core/designsystem/src/main/kotlin/com/dhc/designsystem/tipcard/DhcTipCardGrid.kt
  data/src/main/kotlin/com/dhc/dhcandroid/model/DailyFortuneResponse.kt
  data/src/main/kotlin/com/dhc/dhcandroid/model/FortuneResponse.kt
  presentation/home/src/main/java/com/dhc/home/detail/utils/Extensions.kt
  presentation/home/src/main/java/com/dhc/home/model/TodayDailyFortuneUiModel.kt
Labels: Bug

#439 [#438] 잘 모르겠어요 선택하면 registerUser 가 에러나는 이슈
  data/src/main/kotlin/com/dhc/dhcandroid/di/NetworkModule.kt
  presentation/mypage/src/main/kotlin/com/dhc/mypage/model/MyInfoUiModel.kt
  presentation/mypage/src/main/kotlin/com/dhc/mypage/ui/DateAndTimeOfBirthInfo.kt
  presentation/mypage/src/main/kotlin/com/dhc/mypage/ui/MyPageScreen.kt
Labels: Bug

#454 [#448] 카드 뒤집기 화면 서버정보로 업데이트 하도록 구현, 플레이스홀더 추가
  core/designsystem/src/main/kotlin/com/dhc/designsystem/fortunecard/DhcFortuneCard.kt
  core/designsystem/src/main/res/drawable/fortune_card_placeholder.png
  presentation/home/src/main/java/com/dhc/home/main/HomeFlipCardScreen.kt
Labels: Bug

#460 [#458] 리포트 페이지 디자인 수정
  core/designsystem/src/main/kotlin/com/dhc/designsystem/info/DhcMissionStatusCard.kt
  core/designsystem/src/main/res/drawable/ico_fly_money.xml
  core/designsystem/src/main/res/drawable/ico_hit_target.xml
  presentation/missionstatus/src/main/kotlin/com/dhc/missionstatus/ui/MissionStatusScreen.kt
  presentation/mypage/src/main/kotlin/com/dhc/mypage/ui/SajuCard.kt
Labels: Feature

#461 [#459] 디자인 수정
  core/designsystem/src/main/kotlin/com/dhc/designsystem/gnb/DhcBottomBar.kt
  core/designsystem/src/main/kotlin/com/dhc/designsystem/gnb/DhcGnb.kt
  core/designsystem/src/main/kotlin/com/dhc/designsystem/info/DhcInfo.kt
  core/presentation/src/main/java/com/dhc/presentation/component/MissionTitle.kt
  core/presentation/src/main/java/com/dhc/presentation/ui/monetaryDetail/MonetaryLuckDetailScreen.kt
  presentation/home/src/main/res/values/strings.xml
  presentation/intro/src/main/res/drawable/fortune_card_sample.png
Labels: Bug
