Repository mash-up-kr/DHC-Android, pull requests merged in 2025-06, with the labels that each got.

#76 [#75] 네비게이션 수정
  app/build.gradle.kts
  app/src/main/java/com/dhc/dhcandroid/navigation/DhcApp.kt
  app/src/main/java/com/dhc/dhcandroid/navigation/DhcNavHost.kt
  app/src/main/java/com/dhc/dhcandroid/navigation/DhcNavHostController.kt
  app/src/main/java/com/dhc/dhcandroid/navigation/DhcRoute.kt
  app/src/main/java/com/dhc/dhcandroid/navigation/NavigationExtension.kt
  app/src/main/java/com/dhc/dhcandroid/ui/theme/Theme.kt
  app/src/main/java/com/dhc/dhcandroid/ui/theme/Type.kt
  app/src/test/kotlin/com/dhc/dhcandroid/navigation/DhcRouteTest.kt
  gradle/libs.versions.toml
Labels: Bug

#72 [#71] 인트로 화면 대충 개발
  app/src/main/java/com/dhc/dhcandroid/navigation/DhcNavHost.kt
  app/src/main/java/com/dhc/dhcandroid/navigation/DhcRoute.kt
  presentation/intro/src/main/java/com/dhc/intro/intro/IntroContract.kt
  presentation/intro/src/main/java/com/dhc/intro/intro/IntroRoute.kt
  presentation/intro/src/main/java/com/dhc/intro/intro/IntroScreen.kt
  presentation/intro/src/main/java/com/dhc/intro/intro/IntroViewModel.kt
  presentation/intro/src/main/java/com/dhc/intro/tutorial/TutorialScreen.kt
  presentation/intro/src/main/res/values/strings.xml
Labels: Feature

#101 [#97] 디자인시스템 컬러 정의
  app/src/main/java/com/dhc/dhcandroid/MainActivity.kt
  core/designsystem/src/main/kotlin/com/dhc/designsystem/Color.kt
  core/designsystem/src/main/kotlin/com/dhc/designsystem/Theme.kt
  presentation/intro/src/main/java/com/dhc/intro/intro/IntroScreen.kt
  presentation/intro/src/main/java/com/dhc/intro/splash/SplashScreen.kt
Labels: Feature

#108 [#88] 디자인시스템 - 아이콘 리소스
  core/designsystem/src/main/res/drawable/info_circle.xml
  core/designsystem/src/main/res/drawable/pin.xml
  core/designsystem/src/main/res/drawable/reward.xml
  core/designsystem/src/main/res/drawable/x.xml
Labels: Feature

#106 [#94] 디자인시스템 컴포넌트 - Check
  core/designsystem/src/main/kotlin/com/dhc/designsystem/Color.kt
  core/designsystem/src/main/kotlin/com/dhc/designsystem/check/DhcCheck.kt
  core/designsystem/src/main/kotlin/com/dhc/designsystem/check/model/DhcCheckStyle.kt
  core/designsystem/src/main/res/drawable/check.xml
Labels: Feature

#104 [#103] 디자인시스템 컴포넌트 - GNB 스타일 적용
  app/src/main/java/com/dhc/dhcandroid/navigation/DhcApp.kt
  app/src/main/java/com/dhc/dhcandroid/navigation/DhcRoute.kt
  app/src/main/java/com/dhc/dhcandroid/navigation/ScreenConfigs.kt
  core/designsystem/src/main/kotlin/com/dhc/designsystem/Color.kt
  core/designsystem/src/main/kotlin/com/dhc/designsystem/Typography.kt
  core/designsystem/src/main/kotlin/com/dhc/designsystem/check/DhcCheck.kt
  core/designsystem/src/main/kotlin/com/dhc/designsystem/gnb/DhcBottomBar.kt
  core/designsystem/src/main/kotlin/com/dhc/designsystem/gnb/DhcGnb.kt
  core/designsystem/src/main/kotlin/com/dhc/designsystem/gnb/model/DhcBottomBarState.kt
  core/designsystem/src/main/res/drawable/home.xml
  core/designsystem/src/main/res/drawable/mypage.xml
  core/designsystem/src/main/res/drawable/status.xml
Labels: Feature

#107 [#91] 디자인시스템 컴포넌트 - TopBar
  app/src/main/java/com/dhc/dhcandroid/navigation/DhcApp.kt
  app/src/main/java/com/dhc/dhcandroid/navigation/DhcRoute.kt
  app/src/main/java/com/dhc/dhcandroid/navigation/ScreenConfig.kt
  core/designsystem/src/main/kotlin/com/dhc/designsystem/topbar/DhcBasicTopBar.kt
  core/designsystem/src/main/kotlin/com/dhc/designsystem/topbar/DhcTopBar.kt
  core/designsystem/src/main/kotlin/com/dhc/designsystem/topbar/model/DhcTopBarState.kt
  core/designsystem/src/main/kotlin/com/dhc/designsystem/topbar/model/TopBarPageState.kt
  core/designsystem/src/main/res/drawable/chevron_left.xml
Labels: Feature

#114 [#87] 디자인시스템 컴포넌트 - 캘린더
  core/designsystem/src/main/kotlin/com/dhc/designsystem/calendar/CalendarUtils.kt
  core/designsystem/src/main/kotlin/com/dhc/designsystem/calendar/DhcCalendarController.kt
  core/designsystem/src/main/kotlin/com/dhc/designsystem/calendar/model/DhcCalendarInitialData.kt
  core/designsystem/src/main/kotlin/com/dhc/designsystem/calendar/ui/DhcCalendar.kt
  core/designsystem/src/main/kotlin/com/dhc/designsystem/calendar/ui/DhcCalendarDate.kt
  core/designsystem/src/main/kotlin/com/dhc/designsystem/calendar/ui/DhcCalendarDayOfWeek.kt
  core/designsystem/src/main/kotlin/com/dhc/designsystem/calendar/ui/DhcCalendarHeader.kt
  core/designsystem/src/main/res/drawable/ico_arrow_left.xml
  core/designsystem/src/main/res/drawable/ico_arrow_right.xml
Labels: Feature

#130 [#128] 디자인 시스템 컴포넌트 - 폰트 추가
  core/designsystem/src/main/kotlin/com/dhc/designsystem/Typography.kt
Labels: Feature

#131 [#129] 디자인시스템 - 컬러
  core/designsystem/src/main/kotlin/com/dhc/designsystem/Color.kt
Labels: Feature

#141 [#113] FlippableBox, DhcFortuneCard 추가
  core/designsystem/src/main/kotlin/com/dhc/designsystem/Typography.kt
  core/designsystem/src/main/kotlin/com/dhc/designsystem/fortunecard/DhcFortuneCard.kt
  core/designsystem/src/main/kotlin/com/dhc/designsystem/fortunecard/FlippableBox.kt
Labels: Feature

#149 [#134] 디자인 컴포넌트 - 토스트(Feat. 스낵바)
  core/designsystem/src/main/kotlin/com/dhc/designsystem/DhcSnackBar.kt
  core/designsystem/src/main/kotlin/com/dhc/designsystem/check/model/DhcCheckStyle.kt
Labels: Feature

#148 [#133] 디자인 시스템 컴포넌트 - 금전운 점수, 더보기 버튼
  core/designsystem/src/main/kotlin/com/dhc/designsystem/FortuneCore.kt
  core/designsystem/src/main/kotlin/com/dhc/designsystem/MoreButton.kt
  core/designsystem/src/main/res/values/strings.xml
Labels: Feature

#169 [#168] DhcTitle subtitle 과 title 의 가로범위가 동일하지 않은 이슈 수정
  core/designsystem/src/main/kotlin/com/dhc/designsystem/title/DhcTitle.kt
Labels: Bug

#153 [#146] 공통 컴포넌트 - 말풍선 개발
  core/presentation/src/main/java/com/dhc/presentation/component/WordBalloon.kt
  core/presentation/src/main/java/com/dhc/presentation/component/WordBalloonColorType.kt
Labels: Feature

#176 [#162] 인트로화면 - 미션확인
  app/src/main/java/com/dhc/dhcandroid/navigation/DhcNavHost.kt
  core/presentation/src/main/java/com/dhc/presentation/component/MissionTitle.kt
  presentation/intro/src/main/java/com/dhc/intro/mission/IntroMissionContract.kt
  presentation/intro/src/main/java/com/dhc/intro/mission/IntroMissionRoute.kt
  presentation/intro/src/main/java/com/dhc/intro/mission/IntroMissionScreen.kt
  presentation/intro/src/main/java/com/dhc/intro/mission/IntroMissionViewModel.kt
  presentation/intro/src/main/res/values/strings.xml
Labels: Feature

#175 [#160] 인트로 화면 - 운세카드 화면
  app/src/main/java/com/dhc/dhcandroid/navigation/DhcNavHost.kt
  core/common/src/main/java/com/dhc/common/CalendarUtil.kt
  core/designsystem/src/main/kotlin/com/dhc/designsystem/fortunecard/FlippableBox.kt
  core/designsystem/src/main/kotlin/com/dhc/designsystem/score/DhcScoreText.kt
  core/presentation/src/main/java/com/dhc/presentation/component/MissionTitle.kt
  presentation/intro/src/main/java/com/dhc/intro/fortunecard/IntroFortuneCardContract.kt
  presentation/intro/src/main/java/com/dhc/intro/fortunecard/IntroFortuneCardRoute.kt
  presentation/intro/src/main/java/com/dhc/intro/fortunecard/IntroFortuneCardScreen.kt
  presentation/intro/src/main/java/com/dhc/intro/fortunecard/IntroFortuneCardViewModel.kt
  presentation/intro/src/main/java/com/dhc/intro/mission/IntroMissionContract.kt
  presentation/intro/src/main/java/com/dhc/intro/mission/IntroMissionRoute.kt
  presentation/intro/src/main/java/com/dhc/intro/mission/IntroMissionScreen.kt
  presentation/intro/src/main/java/com/dhc/intro/mission/IntroMissionViewModel.kt
  presentation/intro/src/main/res/values/strings.xml
Labels: Feature

#173 [#89] 인트로 화면 - 시작화면
  app/src/main/java/com/dhc/dhcandroid/navigation/DhcNavHost.kt
  core/common/src/main/java/com/dhc/common/CalendarUtil.kt
  core/designsystem/src/main/kotlin/com/dhc/designsystem/fortunecard/FlippableBox.kt
  core/designsystem/src/main/kotlin/com/dhc/designsystem/score/DhcScoreText.kt
  core/presentation/src/main/java/com/dhc/presentation/component/MissionTitle.kt
  presentation/intro/src/main/java/com/dhc/intro/description/IntroDescriptionContract.kt
  presentation/intro/src/main/java/com/dhc/intro/description/IntroDescriptionRoute.kt
  presentation/intro/src/main/java/com/dhc/intro/description/IntroDescriptionScreen.kt
  presentation/intro/src/main/java/com/dhc/intro/description/IntroDescriptionViewModel.kt
  presentation/intro/src/main/java/com/dhc/intro/fortunecard/IntroFortuneCardContract.kt
  presentation/intro/src/main/java/com/dhc/intro/fortunecard/IntroFortuneCardRoute.kt
  presentation/intro/src/main/java/com/dhc/intro/fortunecard/IntroFortuneCardScreen.kt
  presentation/intro/src/main/java/com/dhc/intro/fortunecard/IntroFortuneCardViewModel.kt
  presentation/intro/src/main/java/com/dhc/intro/intro/IntroContract.kt
  presentation/intro/src/main/java/com/dhc/intro/intro/IntroRoute.kt
  presentation/intro/src/main/java/com/dhc/intro/intro/IntroScreen.kt
  presentation/intro/src/main/java/com/dhc/intro/intro/IntroViewModel.kt
  presentation/intro/src/main/java/com/dhc/intro/mission/IntroMissionContract.kt
  presentation/intro/src/main/java/com/dhc/intro/mission/IntroMissionRoute.kt
  presentation/intro/src/main/java/com/dhc/intro/mission/IntroMissionScreen.kt
  presentation/intro/src/main/java/com/dhc/intro/mission/IntroMissionViewModel.kt
  presentation/intro/src/main/java/com/dhc/intro/start/IntroStartContract.kt
  presentation/intro/src/main/java/com/dhc/intro/start/IntroStartRoute.kt
  presentation/intro/src/main/java/com/dhc/intro/start/IntroStartScreen.kt
  presentation/intro/src/main/java/com/dhc/intro/start/IntroStartViewModel.kt
  presentation/intro/src/main/res/values/strings.xml
Labels: Feature

#183 [#182] coil okhttp 라이브러리 추가
  core/designsystem/build.gradle.kts
  gradle/libs.versions.toml
Labels: Bug

#198 [#172] Feature : 상단 탑 그라디언트 개발
  core/designsystem/src/main/kotlin/com/dhc/designsystem/Color.kt
  presentation/home/src/main/java/com/dhc/home/ui/HomeScreen.kt
Labels: Feature

#190 [#189] 소비 분석 화면 디자인 컴포넌트 개발
  core/designsystem/src/main/kotlin/com/dhc/designsystem/badge/model/BadgeType.kt
  core/designsystem/src/main/kotlin/com/dhc/designsystem/info/DhcMissionInfoCard.kt
  core/designsystem/src/main/kotlin/com/dhc/designsystem/info/DhcMoneyInfoCard.kt
  core/designsystem/src/main/res/drawable/ico_fly_money.xml
Labels: Feature

#197 [#196] 금전운 상세 화면 UI 개발 - 인트로, 홈
  app/src/main/java/com/dhc/dhcandroid/navigation/DhcNavHost.kt
  app/src/main/java/com/dhc/dhcandroid/navigation/DhcRoute.kt
  core/designsystem/src/main/kotlin/com/dhc/designsystem/tipcard/DhcTipCardGrid.kt
  core/presentation/src/main/java/com/dhc/presentation/ui/monetaryDetail/MonetaryLuckDetailScreen.kt
  core/presentation/src/main/java/com/dhc/presentation/ui/monetaryDetail/MonetaryLuckInfo.kt
  core/presentation/src/main/res/values/strings.xml
  presentation/home/src/main/java/com/dhc/home/HomeRoute.kt
  presentation/home/src/main/java/com/dhc/home/HomeViewModel.kt
  presentation/home/src/main/java/com/dhc/home/detail/MonetaryLuckDetailRoute.kt
  presentation/home/src/main/java/com/dhc/home/detail/MonetaryLuckDetailViewModel.kt
  presentation/home/src/main/java/com/dhc/home/detail/MoneyDetailLuckContract.kt
  presentation/home/src/main/java/com/dhc/home/main/FortuneCore.kt
  presentation/home/src/main/java/com/dhc/home/main/HomeContract.kt
  presentation/home/src/main/java/com/dhc/home/main/HomeMissionComponent.kt
  presentation/home/src/main/java/com/dhc/home/main/HomeRoute.kt
  presentation/home/src/main/java/com/dhc/home/main/HomeScreen.kt
  presentation/home/src/main/java/com/dhc/home/main/HomeViewModel.kt
  presentation/home/src/main/java/com/dhc/home/main/MonetaryLuckyInfo.kt
  presentation/home/src/main/java/com/dhc/home/main/MoreButton.kt
Labels: Feature

#187 [#166] 카테고리 입력 화면 구현하기
  app/src/main/java/com/dhc/dhcandroid/navigation/DhcNavHost.kt
  app/src/main/java/com/dhc/dhcandroid/navigation/DhcRoute.kt
  core/designsystem/src/main/kotlin/com/dhc/designsystem/button/DhcButton.kt
  core/designsystem/src/main/kotlin/com/dhc/designsystem/category/DhcCategoryItem.kt
  presentation/intro/src/main/java/com/dhc/intro/category/IntroCategoryContract.kt
  presentation/intro/src/main/java/com/dhc/intro/category/IntroCategoryRoute.kt
  presentation/intro/src/main/java/com/dhc/intro/category/IntroCategoryScreen.kt
  presentation/intro/src/main/java/com/dhc/intro/category/IntroCategoryViewModel.kt
  presentation/intro/src/main/java/com/dhc/intro/category/model/CategoryItem.kt
  presentation/intro/src/main/res/values/strings.xml
  presentation/mypage/src/main/kotlin/com/dhc/mypage/ui/MyPageScreen.kt
Labels: Feature

#220 [#210] 미사용모듈 제거
  presentation/intro/src/main/java/com/dhc/intro/notification/NotificationScreen.kt
  presentation/intro/src/main/java/com/dhc/intro/registration/CategorySettingScreen.kt
  presentation/intro/src/main/java/com/dhc/intro/registration/UserInfoSettingScreen.kt
Labels: Refactory

#230 [#229] 디버그 오류 수정
  data/src/main/kotlin/com/dhc/dhcandroid/di/NetworkModule.kt
  data/src/main/kotlin/com/dhc/dhcandroid/model/ToggleMissionRequest.kt
Labels: Bug

#224 [#204] 홈 TopBar 쪽 Gradient offset Topbar 크기 하드코딩하지 않도록 수정
  presentation/home/src/main/java/com/dhc/home/main/HomeScreen.kt
Labels: Refactory

#235 [#232] github action local.properties 대응
  .github/workflows/build-debug-check.yaml
  .github/workflows/build-release-check.yaml
  .github/workflows/detekt-check.yaml
Labels: Bug

#222 [#214] 뱃지 컴포넌트 색상 변경
  app/src/main/java/com/dhc/dhcandroid/navigation/DhcNavHost.kt
  core/designsystem/src/main/kotlin/com/dhc/designsystem/badge/DhcBadge.kt
  core/designsystem/src/main/kotlin/com/dhc/designsystem/badge/model/BadgeLevelType.kt
  core/designsystem/src/main/kotlin/com/dhc/designsystem/badge/model/BadgeType.kt
Labels: Refactory

#245 [#244] 카테고리 정보 가져오기 Api 및 data model 추가
  data/src/main/kotlin/com/dhc/dhcandroid/model/MissionCategoriesResponse.kt
  data/src/main/kotlin/com/dhc/dhcandroid/service/DhcService.kt
Labels: Feature

#242 [#223] 인트로 전체적으로 design update
  core/designsystem/src/main/kotlin/com/dhc/designsystem/Color.kt
  core/designsystem/src/main/kotlin/com/dhc/designsystem/fortunecard/DhcFortuneCard.kt
  core/designsystem/src/main/kotlin/com/dhc/designsystem/fortunecard/FlippableBox.kt
  core/presentation/src/main/java/com/dhc/presentation/ui/monetaryDetail/MonetaryLuckDetailScreen.kt
  presentation/home/src/main/java/com/dhc/home/main/HomeScreen.kt
  presentation/intro/src/main/java/com/dhc/intro/fortunecard/IntroFortuneCardScreen.kt
  presentation/intro/src/main/java/com/dhc/intro/mission/IntroMissionScreen.kt
  presentation/intro/src/main/res/values/strings.xml
Labels: Feature

#234 [#227] DhcRemote 관련 작업
  app/src/main/AndroidManifest.xml
  core/common/src/main/kotlin/com/dhc/common/DhcResult.kt
  data/src/main/kotlin/com/dhc/dhcandroid/datasource/DhcRemoteDataSource.kt
  data/src/main/kotlin/com/dhc/dhcandroid/datasource/DhcRemoteDataSourceImpl.kt
  data/src/main/kotlin/com/dhc/dhcandroid/di/DatasourceModule.kt
  data/src/main/kotlin/com/dhc/dhcandroid/di/RepositoryModule.kt
  data/src/main/kotlin/com/dhc/dhcandroid/repository/DhcRepository.kt
  data/src/main/kotlin/com/dhc/dhcandroid/repository/DhcRepositoryImpl.kt
  data/src/main/kotlin/com/dhc/dhcandroid/util/RemoteUtils.kt
Labels: Enviroment

#240 [#215] 금전운 상세 버튼 그라디언트 추가
  core/designsystem/src/main/kotlin/com/dhc/designsystem/Color.kt
  core/presentation/src/main/java/com/dhc/presentation/ui/monetaryDetail/MonetaryLuckDetailScreen.kt
Labels: Feature

#237 [#219] Card가 밀려요...ReRoll 구현...
  app/src/main/java/com/dhc/dhcandroid/navigation/DhcNavHost.kt
  core/designsystem/src/main/kotlin/com/dhc/designsystem/mission/DhcCardReRoll.kt
  core/designsystem/src/main/kotlin/com/dhc/designsystem/mission/MissionItemBackGround.kt
  core/designsystem/src/main/kotlin/com/dhc/designsystem/mission/MoneyFortuneMissionCard.kt
  core/designsystem/src/main/res/drawable/ico_change.xml
  core/presentation/src/main/java/com/dhc/presentation/component/MissionTitle.kt
  presentation/home/src/main/java/com/dhc/home/main/HomeMissionComponent.kt
  presentation/home/src/main/java/com/dhc/home/main/HomeScreen.kt
  presentation/home/src/main/java/com/dhc/home/main/MissionChange.kt
  presentation/home/src/main/res/values/strings.xml
  presentation/mypage/src/main/kotlin/com/dhc/mypage/MyPageViewModel.kt
Labels: Feature

#255 [#246] 인트로 카테고리 정보 서버에서 받아오도록 수정
  app/src/main/java/com/dhc/dhcandroid/navigation/DhcNavHost.kt
  core/common/src/main/kotlin/com/dhc/common/DhcResult.kt
  data/src/main/kotlin/com/dhc/dhcandroid/datasource/DhcRemoteDataSource.kt
  data/src/main/kotlin/com/dhc/dhcandroid/datasource/DhcRemoteDataSourceImpl.kt
  data/src/main/kotlin/com/dhc/dhcandroid/model/MissionCategoriesResponse.kt
  data/src/main/kotlin/com/dhc/dhcandroid/repository/DhcRepository.kt
  data/src/main/kotlin/com/dhc/dhcandroid/repository/DhcRepositoryImpl.kt
  data/src/main/kotlin/com/dhc/dhcandroid/service/DhcService.kt
  presentation/intro/src/main/java/com/dhc/intro/category/IntroCategoryScreen.kt
  presentation/intro/src/main/java/com/dhc/intro/category/IntroCategoryViewModel.kt
  presentation/intro/src/main/java/com/dhc/intro/category/model/CategoryItem.kt
Labels: Feature

#264 [#262] App icon 추가
  app/src/main/ic_launcher-playstore.png
  app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  app/src/main/res/mipmap-hdpi/ic_launcher.webp
  app/src/main/res/mipmap-hdpi/ic_launcher_background.webp
  app/src/main/res/mipmap-hdpi/ic_launcher_foreground.webp
  app/src/main/res/mipmap-hdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-mdpi/ic_launcher.webp
  app/src/main/res/mipmap-mdpi/ic_launcher_background.webp
  app/src/main/res/mipmap-mdpi/ic_launcher_foreground.webp
  app/src/main/res/mipmap-mdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xhdpi/ic_launcher_background.webp
  app/src/main/res/mipmap-xhdpi/ic_launcher_foreground.webp
  app/src/main/res/mipmap-xhdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xxhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xxhdpi/ic_launcher_background.webp
  app/src/main/res/mipmap-xxhdpi/ic_launcher_foreground.webp
  app/src/main/res/mipmap-xxhdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xxxhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_background.webp
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_foreground.webp
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.webp
Labels: Feature

#261 [#258] 인트로 회원가입 API 투입
  app/src/main/java/com/dhc/dhcandroid/MainViewModel.kt
  app/src/main/java/com/dhc/dhcandroid/navigation/DhcApp.kt
  data/src/main/kotlin/com/dhc/dhcandroid/datasource/AuthLocalDataSource.kt
  data/src/main/kotlin/com/dhc/dhcandroid/datasource/AuthLocalDataSourceImpl.kt
  data/src/main/kotlin/com/dhc/dhcandroid/datasource/DhcRemoteDataSource.kt
  data/src/main/kotlin/com/dhc/dhcandroid/datasource/DhcRemoteDataSourceImpl.kt
  data/src/main/kotlin/com/dhc/dhcandroid/model/MissionCategoriesResponse.kt
  data/src/main/kotlin/com/dhc/dhcandroid/model/UserProfile.kt
  data/src/main/kotlin/com/dhc/dhcandroid/repository/AuthDataStoreRepository.kt
  data/src/main/kotlin/com/dhc/dhcandroid/repository/AuthDataStoreRepositoryImpl.kt
  data/src/main/kotlin/com/dhc/dhcandroid/repository/DhcRepository.kt
  data/src/main/kotlin/com/dhc/dhcandroid/repository/DhcRepositoryImpl.kt
  data/src/main/kotlin/com/dhc/dhcandroid/repository/UserRepository.kt
  data/src/main/kotlin/com/dhc/dhcandroid/repository/UserRepositoryImpl.kt
  data/src/main/kotlin/com/dhc/dhcandroid/service/DhcService.kt
  data/src/main/proto/user_preferences.proto
  presentation/intro/src/main/java/com/dhc/intro/category/IntroCategoryContract.kt
  presentation/intro/src/main/java/com/dhc/intro/category/IntroCategoryViewModel.kt
  presentation/intro/src/main/java/com/dhc/intro/category/model/CategoryItem.kt
  presentation/mypage/src/main/kotlin/com/dhc/mypage/MyPageViewModel.kt
Labels: Feature

#260 [#259] Feature : 마이페이지 카테고리 서버 데이터 연동
  data/src/main/kotlin/com/dhc/dhcandroid/model/MyPageResponse.kt
  presentation/mypage/src/main/kotlin/com/dhc/mypage/MyPageContract.kt
  presentation/mypage/src/main/kotlin/com/dhc/mypage/MyPageViewModel.kt
  presentation/mypage/src/main/kotlin/com/dhc/mypage/model/MissionCategoryUiModel.kt
  presentation/mypage/src/main/kotlin/com/dhc/mypage/ui/MyPageScreen.kt
Labels: Feature
